#include <algorithm>
#include <fstream>
#include <chrono>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <random>
#include <string>
#include <utility>
#include <vector>

#include "biginteger/BigInteger.h"
#include "biginteger/algorithms/Division.h"
#include "biginteger/algorithms/Multiplication.h"
#include "biginteger/algorithms/Squaring.h"
#include "biginteger/algorithms/division/BurnikelZieglerDivision.h"
#include "biginteger/algorithms/division/FastDivision.h"
#include "biginteger/algorithms/division/NewtonDivision.h"
#include "biginteger/algorithms/multiplication/ClassicMultiplication.h"
#include "biginteger/algorithms/multiplication/ClassicSquare.h"
#include "biginteger/algorithms/multiplication/KaratsubaMultiplication.h"
#include "biginteger/algorithms/multiplication/KaratsubaSquare.h"
#include "biginteger/algorithms/multiplication/NTTMultiplication.h"
#include "biginteger/algorithms/multiplication/NTTSquare.h"
#include "biginteger/algorithms/multiplication/Toom5Multiplication.h"
#include "biginteger/algorithms/multiplication/ToomCookMultiplication.h"
#include "biginteger/common/Comparator.h"
#include "biginteger/common/Util.h"

using namespace BigMath;
using namespace std;

namespace
{
  volatile SizeT sink = 0;

  struct ThresholdSuggestions
  {
    SizeT classicMultTotal = BIGMATH_CLASSIC_MULTIPLICATION_THRESHOLD;
    SizeT classicMinLimb = BIGMATH_CLASSIC_MIN_LIMB_THRESHOLD;
    SizeT classicSkewMinLimb = BIGMATH_CLASSIC_SKEW_MIN_LIMB_THRESHOLD;
    SizeT classicSkewRatio = BIGMATH_CLASSIC_SKEW_RATIO;
    SizeT toom3Total = BIGMATH_TOOM3_MULTIPLICATION_THRESHOLD;
    SizeT toom3SkewRatio = BIGMATH_TOOM3_SKEW_RATIO;
    SizeT nttMultTotal = BIGMATH_NTT_MULTIPLICATION_THRESHOLD;
    SizeT nttCrtTotal = BIGMATH_NTT_CRT_THRESHOLD;
    SizeT nttMfaThreshold = BIGMATH_NTT_MFA_THRESHOLD;
    SizeT nttSquare = BIGMATH_NTT_SQUARE_THRESHOLD;
    SizeT bzDivisor = BIGMATH_BZ_DIVISOR_THRESHOLD;
    SizeT newtonMedium = BIGMATH_NEWTON_MEDIUM_B;
    SizeT newtonSkewNumerator = BIGMATH_NEWTON_SKEW_NUMERATOR;
    SizeT newtonSkewDenominator = BIGMATH_NEWTON_SKEW_DENOMINATOR;
    SizeT newtonHighB = BIGMATH_NEWTON_HIGH_SKEW_B;
    SizeT newtonHighSkewNumerator = BIGMATH_NEWTON_HIGH_SKEW_NUMERATOR;
    SizeT newtonHighSkewDenominator = BIGMATH_NEWTON_HIGH_SKEW_DENOMINATOR;
  };

  vector<DataT> RandomNumber(SizeT limbs, mt19937_64 &gen)
  {
    uniform_int_distribution<uint64_t> digit(0, 0xFFFFFFFFULL);
    vector<DataT> value(limbs);
    for (SizeT i = 0; i < limbs; ++i)
      value[i] = (DataT)digit(gen);
    if (!value.empty())
      value.back() = (DataT)(0x80000000ULL | (digit(gen) & 0x7FFFFFFFULL));
    TrimZeros(value);
    return value.empty() ? vector<DataT>{0} : value;
  }

  template <typename Fn>
  double BestMs(Fn &&fn, int reps)
  {
    double best = numeric_limits<double>::max();
    for (int i = 0; i < reps; ++i)
    {
      auto start = chrono::high_resolution_clock::now();
      SizeT checksum = fn();
      auto end = chrono::high_resolution_clock::now();
      sink += checksum;
      best = min(best, chrono::duration<double, milli>(end - start).count());
    }
    return best;
  }

  int RepsForLimbs(SizeT limbs)
  {
    if (limbs <= 128)
      return 7;
    if (limbs <= 4096)
      return 5;
    return 3;
  }

  string Winner(initializer_list<pair<string, double>> values)
  {
    auto best = values.begin();
    for (auto it = values.begin(); it != values.end(); ++it)
      if (it->second < best->second)
        best = it;
    return best->first;
  }

  void PrintHeader(string const &title)
  {
    cout << "\n== " << title << " ==\n";
  }

  void WriteThresholdHeader(string const &path, ThresholdSuggestions const &s)
  {
    ofstream out(path);
    if (!out)
      throw runtime_error("failed to open dispatch threshold header: " + path);

    out << "#ifndef BIGMATH_DISPATCH_THRESHOLDS\n";
    out << "#define BIGMATH_DISPATCH_THRESHOLDS\n\n";
    out << "// Generated by tests/performance/dispatch_tuner.cpp --emit-header.\n";
    out << "// Regenerate this file after benchmarking on a new compiler or CPU.\n\n";

    out << "#ifndef BIGMATH_CLASSIC_MULTIPLICATION_THRESHOLD\n";
    out << "#if BIGMATH_LIMB_64\n";
    out << "#define BIGMATH_CLASSIC_MULTIPLICATION_THRESHOLD " << s.classicMultTotal << '\n';
    out << "#else\n";
    out << "#define BIGMATH_CLASSIC_MULTIPLICATION_THRESHOLD 0\n";
    out << "#endif\n";
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_CLASSIC_MIN_LIMB_THRESHOLD\n";
    out << "#define BIGMATH_CLASSIC_MIN_LIMB_THRESHOLD " << s.classicMinLimb << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_CLASSIC_SKEW_MIN_LIMB_THRESHOLD\n";
    out << "#define BIGMATH_CLASSIC_SKEW_MIN_LIMB_THRESHOLD " << s.classicSkewMinLimb << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_CLASSIC_SKEW_RATIO\n";
    out << "#define BIGMATH_CLASSIC_SKEW_RATIO " << s.classicSkewRatio << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_TOOM3_MULTIPLICATION_THRESHOLD\n";
    out << "#define BIGMATH_TOOM3_MULTIPLICATION_THRESHOLD " << s.toom3Total << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_TOOM3_SKEW_RATIO\n";
    out << "#define BIGMATH_TOOM3_SKEW_RATIO " << s.toom3SkewRatio << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NTT_MULTIPLICATION_THRESHOLD\n";
    out << "#define BIGMATH_NTT_MULTIPLICATION_THRESHOLD " << s.nttMultTotal << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NTT_CRT_THRESHOLD\n";
    out << "#define BIGMATH_NTT_CRT_THRESHOLD " << s.nttCrtTotal << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NTT_MFA_THRESHOLD\n";
    out << "#define BIGMATH_NTT_MFA_THRESHOLD " << s.nttMfaThreshold << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NTT_SQUARE_THRESHOLD\n";
    out << "#if BIGMATH_LIMB_64\n";
    out << "#define BIGMATH_NTT_SQUARE_THRESHOLD " << s.nttSquare << '\n';
    out << "#else\n";
    out << "#define BIGMATH_NTT_SQUARE_THRESHOLD 512\n";
    out << "#endif\n";
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_BZ_DIVISOR_THRESHOLD\n";
    out << "#define BIGMATH_BZ_DIVISOR_THRESHOLD " << s.bzDivisor << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_MEDIUM_B\n";
    out << "#define BIGMATH_NEWTON_MEDIUM_B " << s.newtonMedium << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_SKEW_NUMERATOR\n";
    out << "#define BIGMATH_NEWTON_SKEW_NUMERATOR " << s.newtonSkewNumerator << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_SKEW_DENOMINATOR\n";
    out << "#define BIGMATH_NEWTON_SKEW_DENOMINATOR " << s.newtonSkewDenominator << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_HIGH_SKEW_B\n";
    out << "#define BIGMATH_NEWTON_HIGH_SKEW_B " << s.newtonHighB << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_HIGH_SKEW_NUMERATOR\n";
    out << "#define BIGMATH_NEWTON_HIGH_SKEW_NUMERATOR " << s.newtonHighSkewNumerator << '\n';
    out << "#endif\n\n";

    out << "#ifndef BIGMATH_NEWTON_HIGH_SKEW_DENOMINATOR\n";
    out << "#define BIGMATH_NEWTON_HIGH_SKEW_DENOMINATOR " << s.newtonHighSkewDenominator << '\n';
    out << "#endif\n\n";

    out << "#endif\n";
  }

  void TuneMultiplication(bool full, ThresholdSuggestions &s)
  {
    PrintHeader("Multiplication Dispatch");
    cout << "limbs_each,total_limbs,classic_ms,karatsuba_ms,toom3_ms,toom5_ms,ntt_ms,winner\n";

    vector<SizeT> sizes = {
        8, 16, 24, 32, 40, 48, 64, 96, 128, 192, 256, 384, 512,
        1024, 2048, 4096, 8192, 12000, 16000};
    if (full)
    {
      sizes.push_back(20000);
      sizes.push_back(24576);
      sizes.push_back(32768);
    }

    mt19937_64 gen(0xB16B00B5);
    SizeT suggestedClassicTotal = CLASSIC_MULTIPLICATION_THRESHOLD;
    SizeT suggestedNttTotal = 0;
    SizeT previousTotal = 0;
    bool foundClassicCrossover = false;
    SizeT suggestedMinLimb = 0;
    bool classicWinsPrefix = true;

    for (SizeT limbs : sizes)
    {
      vector<DataT> a = RandomNumber(limbs, gen);
      vector<DataT> b = RandomNumber(limbs, gen);
      int reps = RepsForLimbs(limbs);

      double classicMs = numeric_limits<double>::quiet_NaN();
      if (limbs <= 256)
      {
        classicMs = BestMs([&]() {
          auto r = ClassicMultiplication::Multiply(a, b, BigInteger::Base());
          return (SizeT)r.size();
        }, reps);
      }

      double karaMs = BestMs([&]() {
        auto r = KaratsubaMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      double toom3Ms = BestMs([&]() {
        auto r = ToomCookMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      double toom5Ms = BestMs([&]() {
        auto r = Toom5Multiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      double nttMs = BestMs([&]() {
        auto r = NTTMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      string winner = limbs <= 256
                          ? Winner({{"classic", classicMs}, {"karatsuba", karaMs}, {"toom3", toom3Ms}, {"toom5", toom5Ms}, {"ntt", nttMs}})
                          : Winner({{"karatsuba", karaMs}, {"toom3", toom3Ms}, {"toom5", toom5Ms}, {"ntt", nttMs}});

      if (!foundClassicCrossover && limbs <= 256 && karaMs < classicMs)
      {
        suggestedClassicTotal = previousTotal;
        foundClassicCrossover = true;
      }
      if (suggestedNttTotal == 0 && nttMs < karaMs)
        suggestedNttTotal = limbs * 2;

      cout << limbs << ',' << limbs * 2 << ','
           << fixed << setprecision(4) << classicMs << ','
           << karaMs << ',' << toom3Ms << ',' << toom5Ms << ',' << nttMs << ','
           << winner << '\n';
      previousTotal = limbs * 2;
    }

    s.classicMultTotal = suggestedClassicTotal;
    s.classicMinLimb = suggestedMinLimb;
    s.nttMultTotal = suggestedNttTotal ? suggestedNttTotal : NTT_MULTIPLICATION_THRESHOLD;

    cout << "suggested CLASSIC_MULTIPLICATION_THRESHOLD ~= "
         << s.classicMultTotal
         << '\n';
    cout << "suggested NTT_MULTIPLICATION_THRESHOLD ~= "
         << s.nttMultTotal
         << '\n';
    cout << "compile override example: -DBIGMATH_CLASSIC_MULTIPLICATION_THRESHOLD="
         << s.classicMultTotal
         << " -DBIGMATH_NTT_MULTIPLICATION_THRESHOLD="
         << s.nttMultTotal
         << '\n';

    PrintHeader("Multiplication Min-Limb Gate");
    cout << "small_limbs,large_limbs,classic_ms,karatsuba_ms,ntt_ms,winner\n";

    vector<SizeT> smallSizes = {4, 8, 16, 24, 32, 40, 48, 64};
    SizeT largeLimbs = full ? 4096 : 1024;

    for (SizeT small : smallSizes)
    {
      vector<DataT> a = RandomNumber(largeLimbs, gen);
      vector<DataT> b = RandomNumber(small, gen);
      int reps = RepsForLimbs(small);

      double classicMs = BestMs([&]() {
        auto r = ClassicMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);
      double karaMs = BestMs([&]() {
        auto r = KaratsubaMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);
      double nttMs = BestMs([&]() {
        auto r = NTTMultiplication::Multiply(a, b, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      string winner = Winner({{"classic", classicMs}, {"karatsuba", karaMs}, {"ntt", nttMs}});
      if (classicWinsPrefix && classicMs * 1.05 < min(karaMs, nttMs))
        suggestedMinLimb = small;
      else
        classicWinsPrefix = false;

      cout << small << ',' << largeLimbs << ','
           << fixed << setprecision(4) << classicMs << ','
           << karaMs << ',' << nttMs << ','
           << winner << '\n';
    }

    cout << "suggested CLASSIC_MIN_LIMB_THRESHOLD ~= "
         << s.classicMinLimb
         << '\n';
    cout << "compile override example: -DBIGMATH_CLASSIC_MIN_LIMB_THRESHOLD="
         << s.classicMinLimb
         << '\n';
  }

  void TuneSquaring(bool full, ThresholdSuggestions &s)
  {
    PrintHeader("Square Dispatch");
    cout << "limbs,classic_ms,karatsuba_ms,ntt_ms,winner\n";

    vector<SizeT> sizes = {
        8, 16, 24, 32, 40, 48, 64, 96, 128, 192, 256, 384, 512,
        768, 1024, 1536, 2048, 4096, 8192};
    if (full)
    {
      sizes.push_back(12000);
      sizes.push_back(16000);
      sizes.push_back(24576);
    }

    mt19937_64 gen(0x5A9E5A9E);
    SizeT suggestedNttSquare = 0;
    SizeT firstNttWin = 0;

    for (SizeT limbs : sizes)
    {
      vector<DataT> a = RandomNumber(limbs, gen);
      int reps = RepsForLimbs(limbs);

      double classicMs = numeric_limits<double>::quiet_NaN();
      if (limbs <= 256)
      {
        classicMs = BestMs([&]() {
          auto r = ClassicSquare::Square(a, BigInteger::Base());
          return (SizeT)r.size();
        }, reps);
      }

      double karaMs = BestMs([&]() {
        auto r = KaratsubaSquare::Square(a, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      double nttMs = BestMs([&]() {
        auto r = NTTSquare::Square(a, BigInteger::Base());
        return (SizeT)r.size();
      }, reps);

      string winner = limbs <= 256
                          ? Winner({{"classic", classicMs}, {"karatsuba", karaMs}, {"ntt", nttMs}})
                          : Winner({{"karatsuba", karaMs}, {"ntt", nttMs}});

      bool nttWinsByMargin = nttMs * 1.05 < karaMs;
      if (nttWinsByMargin)
      {
        if (firstNttWin == 0)
          firstNttWin = limbs;
        else if (suggestedNttSquare == 0)
          suggestedNttSquare = firstNttWin;
      }
      else
      {
        firstNttWin = 0;
      }

      cout << limbs << ','
           << fixed << setprecision(4) << classicMs << ','
           << karaMs << ',' << nttMs << ','
           << winner << '\n';
    }

    s.nttSquare = suggestedNttSquare ? suggestedNttSquare : NTT_SQUARE_THRESHOLD;
    cout << "suggested NTT_SQUARE_THRESHOLD ~= "
         << s.nttSquare
         << '\n';
    cout << "compile override example: -DBIGMATH_NTT_SQUARE_THRESHOLD="
         << s.nttSquare
         << '\n';
  }

  void TuneDivision(bool full, ThresholdSuggestions &s)
  {
    PrintHeader("Division Dispatch");
    cout << "dividend_limbs,divisor_limbs,ratio,fast_ms,bz_ms,newton_ms,winner\n";

    vector<pair<SizeT, double>> cases = {
        {512, 2.0}, {768, 2.0}, {1024, 2.0},
        {2048, 1.5}, {2048, 2.0}, {2048, 3.0},
        {4096, 1.5}, {4096, 2.0}, {4096, 4.0},
        {8192, 1.25}, {8192, 1.5}, {8192, 2.0}, {8192, 4.0},
        {16384, 1.5}, {16384, 2.0},
        {24576, 1.5}};
    if (full)
    {
      cases.push_back({16384, 1.5});
      cases.push_back({24576, 2.0});
      cases.push_back({32768, 1.5});
    }

    mt19937_64 gen(0xD1715100);
    SizeT suggestedBzDivisor = 0;
    SizeT suggestedNewtonMedium = 0;
    SizeT suggestedNewtonSkewNumerator = 0;
    SizeT suggestedNewtonSkewDenominator = 1;

    for (auto const &[divisorLimbs, ratio] : cases)
    {
      SizeT dividendLimbs = max((SizeT)(divisorLimbs + 1), (SizeT)(divisorLimbs * ratio));
      vector<DataT> a = RandomNumber(dividendLimbs, gen);
      vector<DataT> b = RandomNumber(divisorLimbs, gen);
      int reps = RepsForLimbs(divisorLimbs);

      double fastMs = BestMs([&]() {
        auto qr = FastDivision::DivideAndRemainder(a, b, BigInteger::Base(), true);
        return (SizeT)(qr.first.size() + qr.second.size());
      }, reps);

      double bzMs = BestMs([&]() {
        auto qr = BurnikelZieglerDivision::DivideAndRemainder(a, b, BigInteger::Base(), true);
        return (SizeT)(qr.first.size() + qr.second.size());
      }, reps);

      double newtonMs = numeric_limits<double>::quiet_NaN();
      if (divisorLimbs >= 8192)
      {
        newtonMs = BestMs([&]() {
          auto qr = NewtonDivision::DivideAndRemainder(a, b, BigInteger::Base(), true);
          return (SizeT)(qr.first.size() + qr.second.size());
        }, max(1, reps / 2));
      }

      string winner = divisorLimbs >= 8192
                          ? Winner({{"fast", fastMs}, {"bz", bzMs}, {"newton", newtonMs}})
                          : Winner({{"fast", fastMs}, {"bz", bzMs}});

      if (suggestedBzDivisor == 0 && bzMs < fastMs)
        suggestedBzDivisor = divisorLimbs;
      if (suggestedNewtonMedium == 0 && divisorLimbs >= 8192 && ratio >= 2.0 && newtonMs < min(fastMs, bzMs))
        suggestedNewtonMedium = divisorLimbs;
      if (suggestedNewtonSkewNumerator == 0 && divisorLimbs >= 8192 && newtonMs < min(fastMs, bzMs))
      {
        suggestedNewtonSkewNumerator = (SizeT)(ratio * 4.0 + 0.5);
        suggestedNewtonSkewDenominator = 4;
        while (suggestedNewtonSkewDenominator > 1 &&
               suggestedNewtonSkewNumerator % 2 == 0 &&
               suggestedNewtonSkewDenominator % 2 == 0)
        {
          suggestedNewtonSkewNumerator /= 2;
          suggestedNewtonSkewDenominator /= 2;
        }
      }

      cout << dividendLimbs << ',' << divisorLimbs << ','
           << fixed << setprecision(2) << ratio << ','
           << setprecision(4) << fastMs << ',' << bzMs << ',' << newtonMs << ','
           << winner << '\n';
    }

    s.bzDivisor = suggestedBzDivisor ? suggestedBzDivisor : BZ_DIVISOR_THRESHOLD;
    s.newtonMedium = suggestedNewtonMedium ? suggestedNewtonMedium : NEWTON_MEDIUM_B;
    s.newtonSkewNumerator = suggestedNewtonSkewNumerator ? suggestedNewtonSkewNumerator : NEWTON_SKEW_NUMERATOR;
    s.newtonSkewDenominator = suggestedNewtonSkewNumerator ? suggestedNewtonSkewDenominator : NEWTON_SKEW_DENOMINATOR;

    cout << "suggested BZ divisor floor ~= "
         << s.bzDivisor
         << '\n';
    cout << "suggested NEWTON_MEDIUM_B ~= "
         << s.newtonMedium
         << '\n';
    cout << "suggested NEWTON skew ratio ~= "
         << s.newtonSkewNumerator
         << '/'
         << s.newtonSkewDenominator
         << '\n';
    cout << "compile override example: -DBIGMATH_BZ_DIVISOR_THRESHOLD="
         << s.bzDivisor
         << " -DBIGMATH_NEWTON_MEDIUM_B="
         << s.newtonMedium
         << " -DBIGMATH_NEWTON_SKEW_NUMERATOR="
         << s.newtonSkewNumerator
         << " -DBIGMATH_NEWTON_SKEW_DENOMINATOR="
         << s.newtonSkewDenominator
         << '\n';
  }
}

int main(int argc, char **argv)
{
  bool full = false;
  bool emitHeaderRequested = false;
  string emitHeaderPath;

  for (int i = 1; i < argc; ++i)
  {
    string arg = argv[i];
    if (arg == "--full")
    {
      full = true;
      continue;
    }
    if (arg == "--emit-header" && i + 1 < argc)
    {
      emitHeaderRequested = true;
      emitHeaderPath = argv[++i];
      continue;
    }
    if (arg.rfind("--emit-header=", 0) == 0)
    {
      emitHeaderRequested = true;
      emitHeaderPath = arg.substr(string("--emit-header=").size());
      continue;
    }
    if (arg == "--emit-header")
    {
      emitHeaderRequested = true;
      continue;
    }
  }

  if (emitHeaderRequested && emitHeaderPath.empty())
    emitHeaderPath = "include/biginteger/build/DispatchThresholds.h";

  cout << "BigInteger dispatch tuner\n";
  cout << unitbuf;
  cout << "mode=" << (full ? "full" : "quick") << '\n';
  cout << "base=" << BigInteger::Base() << '\n';

  ThresholdSuggestions suggestions;
  TuneMultiplication(full, suggestions);
  TuneSquaring(full, suggestions);
  TuneDivision(full, suggestions);

  if (!emitHeaderPath.empty())
  {
    WriteThresholdHeader(emitHeaderPath, suggestions);
    cout << "wrote dispatch threshold header: " << emitHeaderPath << '\n';
  }

  cerr << "checksum=" << sink << '\n';
  return 0;
}
